apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo
spec:
  template:
    spec:
      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-mehreen-asghar
      containers:
        - name: todo-backend
          volumeMounts:
            - name: kv-secrets
              mountPath: /mnt/secrets
              readOnly: true
